# Generated by Django 3.2.16 on 2022-12-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_name', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Название металла')),
                ('density', models.SmallIntegerField(verbose_name='Плотность металла, кг/м³')),
            ],
            options={
                'verbose_name': 'Металл',
                'verbose_name_plural': 'Металлы',
                'ordering': ('metal_name',),
            },
        ),
        migrations.CreateModel(
            name='MetalShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название профиля')),
            ],
            options={
                'verbose_name': 'Профиль металлопроката',
                'verbose_name_plural': 'Профили металлопроката',
                'ordering': ('shape_name',),
            },
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название страницы')),
                ('description', models.CharField(max_length=150, verbose_name='Описание страницы')),
                ('keywords', models.CharField(max_length=250, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MetalAlloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_alloy', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название сплава')),
                ('density', models.SmallIntegerField(verbose_name='Плотность сплава, кг/м³')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal_calc.metal', verbose_name='Металл')),
            ],
            options={
                'verbose_name': 'Сплав',
                'verbose_name_plural': 'Сплавы',
                'ordering': ('metal', 'metal_alloy'),
            },
        ),
    ]
